import Head from 'next/head'
import Navbar from '../components/Navbar'
import Todo from '../components/Todo';
import { table, minifyRecords} from './api/utils/airtables'
import {TodosContext} from '../contexts/TodosContext';
import {useEffect, useContext} from 'react';
import { useUser, getSession} from '@auth0/nextjs-auth0';
import TodoForm from '../components/TodoForm';



export default function Home({initialTodos, user}) {
  const {todos, setTodos} = useContext(TodosContext);

  useEffect(() => {
    setTodos(initialTodos)
  }, [])

  return (
    <div>
      <Head>
        <title>Authenticated TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        {
          user && (
            <>
              <h1 className="text-2xl text-center mb-4" >Todo App</h1>

              <TodoForm/>
              <ul>
                {todos &&
                  todos.map((todo) => (
                  <Todo key={todo.id} todo={todo}/>
                ))}
              </ul>
            </>
          )
        }
        {
          !user && <p>You&apos;re not logged in boi</p>
        }
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context.req, context.res)
  let todos = [];
  try{
    if(session?.user){
      todos = await table.select({
        filterByFormula: `userID = '${session.user.sub}'`
      }).firstPage();
    }
    return {
      props: {
        initialTodos: minifyRecords(todos),
        user: session?.user || null,
      }
    }
  }catch (err) {
    console.log(err);
    return {
      props: {
        err: "Something went wrong"
      }
    }
  }
}
